cat > patch-firewall.diff <<'PATCH'
*** Begin Patch
*** Update File: scripts/install.sh
@@
 PROJECT_DIR_DEFAULT="$HOME/docker-stacks/firewall_ai"
 SYSTEMD_SRC="$SCRIPT_DIR/../systemd/firewall-ai.service"
 SYSTEMD_DST="/etc/systemd/system/firewall-ai.service"
 PROFILE_REPO_SRC="$SCRIPT_DIR/firewall_ai_profile.sh"
 PROFILE_USER_DST=".firewall_ai_profile"
 MOTD_USER_DST=".firewall_ai_motd"
 LOG_DIR_DEFAULT="$HOME/docker-stacks/firewall_ai/log"
 
 # Flags
 INSTALL_SYSTEMD=false
 INSTALL_SYSTEM_WIDE=false
+GROUP_NAME="firewalladmins"
@@
 TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
 if [ -z "$TARGET_HOME" ]; then
   echo "Impossibile determinare la home di $TARGET_USER" >&2
   exit 1
 fi
@@
 mkdir -p "$LOG_DIR"
 chown -R "$TARGET_USER":"$TARGET_USER" "$PROJECT_DIR" || true
@@
 chown "$TARGET_USER":"$TARGET_USER" "$PROFILE_DST"
 chmod 644 "$PROFILE_DST"
@@
 if ! grep -qxF 'source $HOME/.firewall_ai_profile' "$BASH_PROFILE" 2>/dev/null; then
   echo '' >> "$BASH_PROFILE"
   echo 'source $HOME/.firewall_ai_profile' >> "$BASH_PROFILE"
 fi
@@
 if ! grep -qxF 'source $HOME/.firewall_ai_profile' "$BASHRC" 2>/dev/null; then
   echo '' >> "$BASHRC"
   echo 'source $HOME/.firewall_ai_profile' >> "$BASHRC"
 fi
@@
 chown "$TARGET_USER":"$TARGET_USER" "$MOTD_FILE"
 chmod 644 "$MOTD_FILE"
@@
 mkdir -p "$LOG_DIR"
 chown -R "$TARGET_USER":"$TARGET_USER" "$LOG_DIR"
 chmod 755 "$LOG_DIR"
 
+# -------------------------
+# Helper: create admin group and add user
+# -------------------------
+create_admin_group() {
+  if ! getent group "$GROUP_NAME" >/dev/null 2>&1; then
+    echo "Creazione gruppo $GROUP_NAME"
+    groupadd --system "$GROUP_NAME" || groupadd "$GROUP_NAME" || true
+  fi
+  # Aggiungi l'utente target al gruppo (idempotente)
+  if id -nG "$TARGET_USER" | grep -qw "$GROUP_NAME"; then
+    echo "Utente $TARGET_USER già membro di $GROUP_NAME"
+  else
+    usermod -aG "$GROUP_NAME" "$TARGET_USER" || true
+    echo "Aggiunto $TARGET_USER a $GROUP_NAME"
+  fi
+}
+
+# -------------------------
+# Install systemd unit (requires root)
+# -------------------------
+install_systemd_unit() {
+  local unit_src="$PROJECT_DIR/systemd/firewall-ai.service"
+  local unit_dst="/etc/systemd/system/firewall-ai.service"
+  if [ ! -f "$unit_src" ]; then
+    echo "Unit systemd non trovata in $unit_src"
+    return 1
+  fi
+
+  # Patch ExecStart con percorso reale del repo
+  sed "s|/home/%i/docker-stacks/firewall_ai/firewall_ai.py|$PROJECT_DIR/firewall_ai.py|g" "$unit_src" > /tmp/firewall-ai.service
+  mv /tmp/firewall-ai.service "$unit_dst"
+  chown root:root "$unit_dst"
+  chmod 644 "$unit_dst"
+  systemctl daemon-reload
+  systemctl enable --now firewall-ai.service || true
+  echo "Unit systemd installata e avviata (se possibile)."
+}
+
+# -------------------------
+# Install system-wide profile (requires root)
+# -------------------------
+install_system_profile() {
+  local sys_profile="/etc/profile.d/firewall_ai.sh"
+  cat > "$sys_profile" <<'EOF'
+# firewall_ai global helpers (opt-out with NO_FIREWALL_AI=1)
+# Default: disabled for new users (NO_FIREWALL_AI=1)
+export NO_FIREWALL_AI=1
+if [ -z "${NO_FIREWALL_AI:-}" ]; then
+  FIREWALL_AI_DIR="${FIREWALL_AI_DIR:-/home/roberto/docker-stacks/firewall_ai}"
+  export FIREWALL_AI_DIR
+  export FIREWALL_AI_RULES="$FIREWALL_AI_DIR/rules/firewall.rules"
+  alias fw-dry="python3 \$FIREWALL_AI_DIR/firewall_ai.py --dry-run"
+  alias fw-apply="sudo python3 \$FIREWALL_AI_DIR/firewall_ai.py"
+  alias fw-list="sudo nft list chain inet filter input -a"
+fi
+EOF
+  chmod 644 "$sys_profile"
+  echo "Profile system-wide installato in $sys_profile (NO_FIREWALL_AI=1 di default)."
+}
+
+# -------------------------
+# Install sudoers snippet for group (requires root)
+# -------------------------
+install_sudoers() {
+  local sudoers_file="/etc/sudoers.d/firewall_ai"
+  cat > "$sudoers_file" <<EOF
+# firewall_ai sudoers (generated by install.sh)
+%$GROUP_NAME ALL=(root) NOPASSWD: /usr/bin/python3 $PROJECT_DIR/firewall_ai.py, /usr/sbin/nft
+EOF
+  chmod 440 "$sudoers_file"
+  echo "Sudoers snippet installato in $sudoers_file (gruppo: $GROUP_NAME)."
+}
+
+# -------------------------
+# Conditional calls for system install
+# -------------------------
+if [ "$INSTALL_SYSTEMD" = true ]; then
+  if [ "$(id -u)" -ne 0 ]; then
+    echo "--systemd richiede sudo. Rilancia con sudo." >&2
+    exit 1
+  fi
+  create_admin_group
+  install_systemd_unit
+  install_sudoers
+fi
+
+if [ "$INSTALL_SYSTEM_WIDE" = true ]; then
+  if [ "$(id -u)" -ne 0 ]; then
+    echo "--system richiede sudo. Rilancia con sudo." >&2
+    exit 1
+  fi
+  create_admin_group
+  install_system_profile
+  install_sudoers
+fi
+
*** End Patch
PATCH
